"""Add comprehensive schema

Revision ID: 1242ef6cbc30
Revises: 
Create Date: 2026-01-05 00:15:22.126443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1242ef6cbc30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    # Add updated_at with a temporary default, then update existing rows
    op.execute("ALTER TABLE users ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE")
    op.execute("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL")
    op.execute("ALTER TABLE users ALTER COLUMN updated_at SET NOT NULL")
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
